// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
    production: false,
    path: {
        matchs: {
            url: 'assets/files/partidos.txt',
            url8: 'assets/files/partidos_8.txt',
            separator: {
                row: '/\r\n|\n|\r|\\n/g',
                team: ',',
            },
        },
        columns: {
            url: 'assets/files/columnas.txt',
            url8: 'assets/files/columnas_8.txt',
            separator: '/\r\n|\n|\r|\\n/g',
        },
    },
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
// [
//   {
//     fecha_sorteo: '2020-06-28 00:00:00',
//     dia_semana: 'domingo',
//     id_sorteo: '1095606018',
//     game_id: 'LAQU',
//     anyo: '2020',
//     numero: 18,
//     premio_bote: '1500000',
//     cdc: '10956',
//     apuestas: '0',
//     recaudacion: null,
//     combinacion: null,
//     premios: '0',
//     fondo_bote: '96086781',
//     escrutinio: [],
//     partidos: [
//       {
//         posicion: 1,
//         idLocal: 1,
//         local: 'Athletic Club',
//         idVisitante: 10,
//         visitante: 'Mallorca',
//         signo: '1',
//         marcador: '3 - 1',
//         fecha: '27-06-2020',
//         hora: '14:00',
//         fecha_completa: '2020-06-27 14:00:00',
//       },
//       {
//         posicion: 2,
//         idLocal: 111,
//         local: 'Celta',
//         idVisitante: 4,
//         visitante: 'Barcelona',
//         signo: 'X',
//         marcador: '2 - 2',
//         fecha: '27-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-27 17:00:00',
//       },
//       {
//         posicion: 3,
//         idLocal: 2,
//         local: 'Osasuna',
//         idVisitante: 1151,
//         visitante: 'Legan\u00e9s',
//         signo: '1',
//         marcador: '2 - 1',
//         fecha: '27-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-27 19:30:00',
//       },
//       {
//         posicion: 4,
//         idLocal: 3,
//         local: 'At. Madrid',
//         idVisitante: 374,
//         visitante: 'Alav\u00e9s',
//         signo: '1',
//         marcador: '2 - 1',
//         fecha: null,
//         hora: null,
//         fecha_completa: null,
//       },
//       {
//         posicion: 5,
//         idLocal: 6,
//         local: 'Levante',
//         idVisitante: 11,
//         visitante: 'Betis',
//         signo: null,
//         marcador: null,
//         fecha: '28-06-2020',
//         hora: '14:00',
//         fecha_completa: '2020-06-28 14:00:00',
//       },
//       {
//         posicion: 6,
//         idLocal: 20,
//         local: 'Villarreal',
//         idVisitante: 19,
//         visitante: 'Valencia',
//         signo: null,
//         marcador: null,
//         fecha: '28-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-28 17:00:00',
//       },
//       {
//         posicion: 7,
//         idLocal: 564,
//         local: 'Granada',
//         idVisitante: 124,
//         visitante: 'Eibar',
//         signo: null,
//         marcador: null,
//         fecha: '28-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-28 19:30:00',
//       },
//       {
//         posicion: 8,
//         idLocal: 9,
//         local: 'Espanyol',
//         idVisitante: 12,
//         visitante: 'Real Madrid',
//         signo: null,
//         marcador: null,
//         fecha: '28-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-28 22:00:00',
//       },
//       {
//         posicion: 9,
//         idLocal: 110,
//         local: 'C\u00e1diz',
//         idVisitante: 108,
//         visitante: 'Tenerife',
//         signo: '2',
//         marcador: '0 - 2',
//         fecha: '27-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-27 19:30:00',
//       },
//       {
//         posicion: 10,
//         idLocal: 126,
//         local: 'Las Palmas',
//         idVisitante: 131,
//         visitante: 'Elche',
//         signo: 'X',
//         marcador: '1 - 1',
//         fecha: '27-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-27 19:30:00',
//       },
//       {
//         posicion: 11,
//         idLocal: 965,
//         local: 'Mirand\u00e9s',
//         idVisitante: 18,
//         visitante: 'Almer\u00eda',
//         signo: null,
//         marcador: null,
//         fecha: '28-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-28 17:00:00',
//       },
//       {
//         posicion: 12,
//         idLocal: 107,
//         local: 'Sporting',
//         idVisitante: 826,
//         visitante: 'Lugo',
//         signo: null,
//         marcador: null,
//         fecha: '28-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-28 17:00:00',
//       },
//       {
//         posicion: 13,
//         idLocal: 113,
//         local: 'M\u00e1laga',
//         idVisitante: 166,
//         visitante: 'Girona',
//         signo: null,
//         marcador: null,
//         fecha: '28-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-28 19:30:00',
//       },
//       {
//         posicion: 14,
//         idLocal: 120,
//         local: 'Numancia',
//         idVisitante: 1000,
//         visitante: 'R. Oviedo',
//         signo: null,
//         marcador: null,
//         fecha: '28-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-28 19:30:00',
//       },
//       {
//         posicion: 15,
//         idLocal: 5,
//         local: 'Getafe',
//         idVisitante: 125,
//         visitante: 'Real Sociedad',
//         signo: null,
//         marcador: null,
//         fecha: '29-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-29 22:00:00',
//       },
//     ],
//     temporada: '2019-2020',
//     jornada: '46',
//     contenidosRelacionados: {
//       noticias: [
//         {
//           tituloRelacion: 'Bote Automatico',
//           tituloContenido: 'La Quiniela: bote de 1.500.000\u20ac',
//           urlContenido:
//             '/la-quiniela/botes/la-quiniela-bote-de-1-500-000euro-28-de-junio-de-2020',
//         },
//       ],
//       enlaces: [],
//       puntosDeVenta: [],
//       documentos: [],
//       imagenes: [],
//       preguntasFrecuentes: [],
//       paginasLibres: [],
//     },
//     elige8: { gameid: 'ELG8', relsorteoid_asociado: '1095613018', activo: '1' },
//     escrutinioElige8: [],
//   },
//   {
//     fecha_sorteo: '2020-06-24 00:13:00',
//     dia_semana: 'mi\u00e9rcoles',
//     id_sorteo: '1095206017',
//     game_id: 'LAQU',
//     anyo: '2020',
//     numero: 17,
//     premio_bote: '0',
//     cdc: '10942',
//     apuestas: '2100928',
//     recaudacion: '157569600',
//     combinacion: '2 - X - 1 - 2 - 2 - 1 - 1 - 2 - 1 - X - 1 - X - 2 - X - 20',
//     premios: '86663280',
//     fondo_bote: '0',
//     escrutinio: [
//       { tipo: 'Pleno al 15 ', categoria: 1, premio: '0', ganadores: '0' },
//       {
//         tipo: '1\u00aa (14 Aciertos) ',
//         categoria: 2,
//         premio: '0',
//         ganadores: '0',
//       },
//       {
//         tipo: '2\u00aa (13 Aciertos) ',
//         categoria: 3,
//         premio: '4924,05',
//         ganadores: '24',
//       },
//       {
//         tipo: '3\u00aa (12 Aciertos) ',
//         categoria: 4,
//         premio: '331,96',
//         ganadores: '356',
//       },
//       {
//         tipo: '4\u00aa (11 Aciertos) ',
//         categoria: 5,
//         premio: '39,24',
//         ganadores: '3012',
//       },
//       {
//         tipo: '5\u00aa (10 Aciertos) ',
//         categoria: 6,
//         premio: '7,88',
//         ganadores: '17986',
//       },
//     ],
//     partidos: [
//       {
//         posicion: 1,
//         idLocal: 6,
//         local: 'Levante',
//         idVisitante: 3,
//         visitante: 'At. Madrid',
//         signo: '2 ',
//         marcador: '0 - 1',
//         fecha: '23-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-23 19:30:00',
//       },
//       {
//         posicion: 2,
//         idLocal: 15,
//         local: 'Valladolid',
//         idVisitante: 5,
//         visitante: 'Getafe',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '23-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-23 19:30:00',
//       },
//       {
//         posicion: 3,
//         idLocal: 4,
//         local: 'Barcelona',
//         idVisitante: 1,
//         visitante: 'Athletic Club',
//         signo: '1 ',
//         marcador: '1 - 0',
//         fecha: '23-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-23 22:00:00',
//       },
//       {
//         posicion: 4,
//         idLocal: 374,
//         local: 'Alav\u00e9s',
//         idVisitante: 2,
//         visitante: 'Osasuna',
//         signo: '2 ',
//         marcador: '0 - 1',
//         fecha: '24-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-24 19:30:00',
//       },
//       {
//         posicion: 5,
//         idLocal: 125,
//         local: 'Real Sociedad',
//         idVisitante: 111,
//         visitante: 'Celta',
//         signo: '2 ',
//         marcador: '0 - 1',
//         fecha: '24-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-24 19:30:00',
//       },
//       {
//         posicion: 6,
//         idLocal: 124,
//         local: 'Eibar',
//         idVisitante: 19,
//         visitante: 'Valencia',
//         signo: '1 ',
//         marcador: '1 - 0',
//         fecha: '25-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-25 19:30:00',
//       },
//       {
//         posicion: 7,
//         idLocal: 11,
//         local: 'Betis',
//         idVisitante: 9,
//         visitante: 'Espanyol',
//         signo: '1 ',
//         marcador: '1 - 0',
//         fecha: '25-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-25 22:00:00',
//       },
//       {
//         posicion: 8,
//         idLocal: 2951,
//         local: 'Extremadura',
//         idVisitante: 3017,
//         visitante: 'R. Zaragoza',
//         signo: '2 ',
//         marcador: '1 - 2',
//         fecha: '23-06-2020',
//         hora: '21:45',
//         fecha_completa: '2020-06-23 21:45:00',
//       },
//       {
//         posicion: 9,
//         idLocal: 166,
//         local: 'Girona',
//         idVisitante: 120,
//         visitante: 'Numancia',
//         signo: '1 ',
//         marcador: '2 - 0',
//         fecha: '24-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-24 19:30:00',
//       },
//       {
//         posicion: 10,
//         idLocal: 200,
//         local: 'Huesca',
//         idVisitante: 110,
//         visitante: 'C\u00e1diz',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '24-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-24 19:30:00',
//       },
//       {
//         posicion: 11,
//         idLocal: 108,
//         local: 'Tenerife',
//         idVisitante: 965,
//         visitante: 'Mirand\u00e9s',
//         signo: '1 ',
//         marcador: '4 - 1',
//         fecha: '24-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-24 19:30:00',
//       },
//       {
//         posicion: 12,
//         idLocal: 745,
//         local: 'Ponferradina',
//         idVisitante: 14,
//         visitante: 'Racing',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '24-06-2020',
//         hora: '21:45',
//         fecha_completa: '2020-06-24 21:45:00',
//       },
//       {
//         posicion: 13,
//         idLocal: 18,
//         local: 'Almer\u00eda',
//         idVisitante: 604,
//         visitante: 'Alcorc\u00f3n',
//         signo: '2 ',
//         marcador: '0 - 1',
//         fecha: '25-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-25 19:30:00',
//       },
//       {
//         posicion: 14,
//         idLocal: 156,
//         local: 'Rayo Vallecano',
//         idVisitante: 107,
//         visitante: 'Sporting',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '25-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-25 19:30:00',
//       },
//       {
//         posicion: 15,
//         idLocal: 12,
//         local: 'Real Madrid',
//         idVisitante: 10,
//         visitante: 'Mallorca',
//         signo: '2-0',
//         marcador: '2 - 0',
//         fecha: '24-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-24 22:00:00',
//       },
//     ],
//     temporada: '2019-2020',
//     jornada: '45',
//     contenidosRelacionados: {
//       noticias: [
//         {
//           tituloRelacion: 'Resultado Automatico',
//           tituloContenido: 'La Quiniela: resultados del 24 de junio de 2020',
//           urlContenido:
//             '/la-quiniela/resultados/la-quiniela-resultados-del-24-de-junio-de-2020',
//         },
//         {
//           tituloRelacion: 'Escrutinio Automatico',
//           tituloContenido:
//             'La Quiniela: premios y ganadores del 24 de junio de 2020',
//           urlContenido:
//             '/la-quiniela/escrutinios/la-quiniela-premios-y-ganadores-del-24-de-junio-de-2020',
//         },
//       ],
//       enlaces: [],
//       puntosDeVenta: [],
//       documentos: [
//         {
//           tituloRelacion: null,
//           tituloContenido:
//             'Nota de prensa de la jornada del 24/06/2020 La Quiniela',
//           urlContenido:
//             '/f/loterias/documentos/Quiniela/Notas de prensa/NOTA_DE_PRENSA_DE_LA_QUINIELA_DE_FECHA_24_6_20.pdf',
//         },
//       ],
//       imagenes: [],
//       preguntasFrecuentes: [],
//       paginasLibres: [],
//     },
//     elige8: { gameid: 'ELG8', relsorteoid_asociado: '1095213017', activo: '1' },
//     escrutinioElige8: [
//       {
//         tipo: '8 Acertados 8 ',
//         categoria: 1,
//         premio: '911,63',
//         ganadores: '31',
//       },
//     ],
//   },
//   {
//     fecha_sorteo: '2020-06-20 23:58:00',
//     dia_semana: 's\u00e1bado',
//     id_sorteo: '1094806016',
//     game_id: 'LAQU',
//     anyo: '2020',
//     numero: 16,
//     premio_bote: '1000000',
//     cdc: '10948',
//     apuestas: '2659102',
//     recaudacion: '199432650',
//     combinacion: '2 - X - X - 2 - 1 - X - 1 - 1 - 1 - X - 2 - 2 - X - X - 12',
//     premios: '109687958',
//     fondo_bote: '49220108',
//     escrutinio: [
//       { tipo: 'Pleno al 15 ', categoria: 1, premio: '0', ganadores: '0' },
//       {
//         tipo: '1\u00aa (14 Aciertos) ',
//         categoria: 2,
//         premio: '0',
//         ganadores: '0',
//       },
//       {
//         tipo: '2\u00aa (13 Aciertos) ',
//         categoria: 3,
//         premio: '18696,81',
//         ganadores: '8',
//       },
//       {
//         tipo: '3\u00aa (12 Aciertos) ',
//         categoria: 4,
//         premio: '917,63',
//         ganadores: '163',
//       },
//       {
//         tipo: '4\u00aa (11 Aciertos) ',
//         categoria: 5,
//         premio: '88,09',
//         ganadores: '1698',
//       },
//       {
//         tipo: '5\u00aa (10 Aciertos) ',
//         categoria: 6,
//         premio: '17,23',
//         ganadores: '10417',
//       },
//     ],
//     partidos: [
//       {
//         posicion: 1,
//         idLocal: 564,
//         local: 'Granada',
//         idVisitante: 20,
//         visitante: 'Villarreal',
//         signo: '2 ',
//         marcador: '0 - 1',
//         fecha: '19-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-19 19:30:00',
//       },
//       {
//         posicion: 2,
//         idLocal: 10,
//         local: 'Mallorca',
//         idVisitante: 1151,
//         visitante: 'Legan\u00e9s',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '19-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-19 19:30:00',
//       },
//       {
//         posicion: 3,
//         idLocal: 17,
//         local: 'Sevilla',
//         idVisitante: 4,
//         visitante: 'Barcelona',
//         signo: 'X ',
//         marcador: '0 - 0',
//         fecha: '19-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-19 22:00:00',
//       },
//       {
//         posicion: 4,
//         idLocal: 9,
//         local: 'Espanyol',
//         idVisitante: 6,
//         visitante: 'Levante',
//         signo: '2 ',
//         marcador: '1 - 3',
//         fecha: '20-06-2020',
//         hora: '14:00',
//         fecha_completa: '2020-06-20 14:00:00',
//       },
//       {
//         posicion: 5,
//         idLocal: 1,
//         local: 'Athletic Club',
//         idVisitante: 11,
//         visitante: 'Betis',
//         signo: '1 ',
//         marcador: '1 - 0',
//         fecha: '20-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-20 17:00:00',
//       },
//       {
//         posicion: 6,
//         idLocal: 5,
//         local: 'Getafe',
//         idVisitante: 124,
//         visitante: 'Eibar',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '20-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-20 19:30:00',
//       },
//       {
//         posicion: 7,
//         idLocal: 3,
//         local: 'At. Madrid',
//         idVisitante: 15,
//         visitante: 'Valladolid',
//         signo: '1 ',
//         marcador: '1 - 0',
//         fecha: '20-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-20 22:00:00',
//       },
//       {
//         posicion: 8,
//         idLocal: 111,
//         local: 'Celta',
//         idVisitante: 374,
//         visitante: 'Alav\u00e9s',
//         signo: '1 ',
//         marcador: '6 - 0',
//         fecha: '21-06-2020',
//         hora: '14:00',
//         fecha_completa: '2020-06-21 14:00:00',
//       },
//       {
//         posicion: 9,
//         idLocal: 19,
//         local: 'Valencia',
//         idVisitante: 2,
//         visitante: 'Osasuna',
//         signo: '1 ',
//         marcador: '2 - 0',
//         fecha: '21-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-21 19:30:00',
//       },
//       {
//         posicion: 10,
//         idLocal: 7,
//         local: 'Deportivo',
//         idVisitante: 156,
//         visitante: 'Rayo Vallecano',
//         signo: 'X ',
//         marcador: '3 - 3',
//         fecha: '20-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-20 17:00:00',
//       },
//       {
//         posicion: 11,
//         idLocal: 3017,
//         local: 'R. Zaragoza',
//         idVisitante: 18,
//         visitante: 'Almer\u00eda',
//         signo: '2 ',
//         marcador: '0 - 2',
//         fecha: '20-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-20 19:30:00',
//       },
//       {
//         posicion: 12,
//         idLocal: 965,
//         local: 'Mirand\u00e9s',
//         idVisitante: 745,
//         visitante: 'Ponferradina',
//         signo: '2 ',
//         marcador: '1 - 2',
//         fecha: '21-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-21 17:00:00',
//       },
//       {
//         posicion: 13,
//         idLocal: 105,
//         local: 'Albacete',
//         idVisitante: 200,
//         visitante: 'Huesca',
//         signo: 'X ',
//         marcador: '2 - 2',
//         fecha: '21-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-21 19:30:00',
//       },
//       {
//         posicion: 14,
//         idLocal: 110,
//         local: 'C\u00e1diz',
//         idVisitante: 604,
//         visitante: 'Alcorc\u00f3n',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '21-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-21 19:30:00',
//       },
//       {
//         posicion: 15,
//         idLocal: 125,
//         local: 'Real Sociedad',
//         idVisitante: 12,
//         visitante: 'Real Madrid',
//         signo: '1-2',
//         marcador: '1 - 2',
//         fecha: '21-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-21 22:00:00',
//       },
//     ],
//     temporada: '2019-2020',
//     jornada: '44',
//     contenidosRelacionados: {
//       noticias: [
//         {
//           tituloRelacion: 'Resultado Automatico',
//           tituloContenido: 'La Quiniela: resultados del 20 de junio de 2020',
//           urlContenido:
//             '/la-quiniela/resultados/la-quiniela-resultados-del-20-de-junio-de-2020',
//         },
//         {
//           tituloRelacion: 'Escrutinio Automatico',
//           tituloContenido:
//             'La Quiniela: premios y ganadores del 20 de junio de 2020',
//           urlContenido:
//             '/la-quiniela/escrutinios/la-quiniela-premios-y-ganadores-del-20-de-junio-de-2020',
//         },
//         {
//           tituloRelacion: 'Bote Automatico',
//           tituloContenido: 'La Quiniela: bote de 1.000.000\u20ac',
//           urlContenido:
//             '/la-quiniela/botes/la-quiniela-bote-de-1-000-000euro-20-de-junio-de-2020',
//         },
//       ],
//       enlaces: [],
//       puntosDeVenta: [],
//       documentos: [
//         {
//           tituloRelacion: null,
//           tituloContenido:
//             'Nota de prensa de la jornada del 20/06/2020 La Quiniela',
//           urlContenido:
//             '/f/loterias/documentos/Quiniela/Temporada_2019_2020/NOTA_DE_PRENSA_DE_LA_QUINIELA_DE_FECHA_20_6_20.pdf',
//         },
//       ],
//       imagenes: [],
//       preguntasFrecuentes: [],
//       paginasLibres: [],
//     },
//     elige8: { gameid: 'ELG8', relsorteoid_asociado: '1094813016', activo: '1' },
//     escrutinioElige8: [
//       {
//         tipo: '8 Acertados 8 ',
//         categoria: 1,
//         premio: '1637,1',
//         ganadores: '19',
//       },
//     ],
//   },
//   {
//     fecha_sorteo: '2020-06-17 00:01:00',
//     dia_semana: 'mi\u00e9rcoles',
//     id_sorteo: '1094506015',
//     game_id: 'LAQU',
//     anyo: '2020',
//     numero: 15,
//     premio_bote: '0',
//     cdc: '10945',
//     apuestas: '2124784',
//     recaudacion: '159358800',
//     combinacion: 'X - 1 - 1 - X - X - 2 - 1 - 2 - X - X - 1 - 2 - 2 - 2 - M0',
//     premios: '87647340',
//     fondo_bote: '0',
//     escrutinio: [
//       { tipo: 'Pleno al 15 ', categoria: 1, premio: '0', ganadores: '0' },
//       {
//         tipo: '1\u00aa (14 Aciertos) ',
//         categoria: 2,
//         premio: '254974,08',
//         ganadores: '1',
//       },
//       {
//         tipo: '2\u00aa (13 Aciertos) ',
//         categoria: 3,
//         premio: '3983,97',
//         ganadores: '30',
//       },
//       {
//         tipo: '3\u00aa (12 Aciertos) ',
//         categoria: 4,
//         premio: '288',
//         ganadores: '415',
//       },
//       {
//         tipo: '4\u00aa (11 Aciertos) ',
//         categoria: 5,
//         premio: '31,69',
//         ganadores: '3771',
//       },
//       {
//         tipo: '5\u00aa (10 Aciertos) ',
//         categoria: 6,
//         premio: '6,23',
//         ganadores: '23011',
//       },
//     ],
//     partidos: [
//       {
//         posicion: 1,
//         idLocal: 5,
//         local: 'Getafe',
//         idVisitante: 9,
//         visitante: 'Espanyol',
//         signo: 'X ',
//         marcador: '0 - 0',
//         fecha: '16-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-16 19:30:00',
//       },
//       {
//         posicion: 2,
//         idLocal: 20,
//         local: 'Villarreal',
//         idVisitante: 10,
//         visitante: 'Mallorca',
//         signo: '1 ',
//         marcador: '1 - 0',
//         fecha: '16-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-16 19:30:00',
//       },
//       {
//         posicion: 3,
//         idLocal: 4,
//         local: 'Barcelona',
//         idVisitante: 1151,
//         visitante: 'Legan\u00e9s',
//         signo: '1 ',
//         marcador: '2 - 0',
//         fecha: '16-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-16 22:00:00',
//       },
//       {
//         posicion: 4,
//         idLocal: 124,
//         local: 'Eibar',
//         idVisitante: 1,
//         visitante: 'Athletic Club',
//         signo: 'X ',
//         marcador: '2 - 2',
//         fecha: '17-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-17 19:30:00',
//       },
//       {
//         posicion: 5,
//         idLocal: 15,
//         local: 'Valladolid',
//         idVisitante: 111,
//         visitante: 'Celta',
//         signo: 'X ',
//         marcador: '0 - 0',
//         fecha: '17-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-17 19:30:00',
//       },
//       {
//         posicion: 6,
//         idLocal: 2,
//         local: 'Osasuna',
//         idVisitante: 3,
//         visitante: 'At. Madrid',
//         signo: '2 ',
//         marcador: '0 - 5',
//         fecha: '17-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-17 22:00:00',
//       },
//       {
//         posicion: 7,
//         idLocal: 374,
//         local: 'Alav\u00e9s',
//         idVisitante: 125,
//         visitante: 'Real Sociedad',
//         signo: '1 ',
//         marcador: '2 - 0',
//         fecha: '18-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-18 19:30:00',
//       },
//       {
//         posicion: 8,
//         idLocal: 826,
//         local: 'Lugo',
//         idVisitante: 16,
//         visitante: 'Zaragoza',
//         signo: '2 ',
//         marcador: '1 - 3',
//         fecha: '16-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-16 19:30:00',
//       },
//       {
//         posicion: 9,
//         idLocal: 166,
//         local: 'Girona',
//         idVisitante: 14,
//         visitante: 'Racing',
//         signo: 'X ',
//         marcador: '0 - 0',
//         fecha: '16-06-2020',
//         hora: '21:45',
//         fecha_completa: '2020-06-16 21:45:00',
//       },
//       {
//         posicion: 10,
//         idLocal: 1000,
//         local: 'R. Oviedo',
//         idVisitante: 7,
//         visitante: 'Deportivo',
//         signo: 'X ',
//         marcador: '2 - 2',
//         fecha: '17-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-17 19:30:00',
//       },
//       {
//         posicion: 11,
//         idLocal: 156,
//         local: 'Rayo Vallecano',
//         idVisitante: 2589,
//         visitante: 'Fuenlabrada',
//         signo: '1 ',
//         marcador: '1 - 0',
//         fecha: '17-06-2020',
//         hora: '21:45',
//         fecha_completa: '2020-06-17 21:45:00',
//       },
//       {
//         posicion: 12,
//         idLocal: 200,
//         local: 'Huesca',
//         idVisitante: 965,
//         visitante: 'Mirand\u00e9s',
//         signo: '2 ',
//         marcador: '1 - 2',
//         fecha: '18-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-18 19:30:00',
//       },
//       {
//         posicion: 13,
//         idLocal: 120,
//         local: 'Numancia',
//         idVisitante: 110,
//         visitante: 'C\u00e1diz',
//         signo: '2 ',
//         marcador: '1 - 2',
//         fecha: '18-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-18 19:30:00',
//       },
//       {
//         posicion: 14,
//         idLocal: 604,
//         local: 'Alcorc\u00f3n',
//         idVisitante: 107,
//         visitante: 'Sporting',
//         signo: '2 ',
//         marcador: '0 - 2',
//         fecha: '18-06-2020',
//         hora: '21:45',
//         fecha_completa: '2020-06-18 21:45:00',
//       },
//       {
//         posicion: 15,
//         idLocal: 12,
//         local: 'Real Madrid',
//         idVisitante: 19,
//         visitante: 'Valencia',
//         signo: 'M-0',
//         marcador: '3 - 0',
//         fecha: '18-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-18 22:00:00',
//       },
//     ],
//     temporada: '2019-2020',
//     jornada: '43',
//     contenidosRelacionados: {
//       noticias: [
//         {
//           tituloRelacion: 'Resultado Automatico',
//           tituloContenido: 'La Quiniela: resultados del 17 de junio de 2020',
//           urlContenido:
//             '/la-quiniela/resultados/la-quiniela-resultados-del-17-de-junio-de-2020',
//         },
//         {
//           tituloRelacion: 'Escrutinio Automatico',
//           tituloContenido:
//             'La Quiniela: premios y ganadores del 17 de junio de 2020',
//           urlContenido:
//             '/la-quiniela/escrutinios/la-quiniela-premios-y-ganadores-del-17-de-junio-de-2020',
//         },
//         {
//           tituloRelacion: 'Premio Automatico 2',
//           tituloContenido:
//             'Premio de 14 aciertos de La Quiniela del 17 de junio de 2020',
//           urlContenido:
//             '/premios/premio-de-14-aciertos-de-la-quiniela-del-17-de-junio-de-2020',
//         },
//       ],
//       enlaces: [],
//       puntosDeVenta: [],
//       documentos: [
//         {
//           tituloRelacion: null,
//           tituloContenido:
//             'Nota de prensa de la jornada del 17/06/2020 La Quiniela',
//           urlContenido:
//             '/f/loterias/documentos/Quiniela/Temporada_2019_2020/NOTA_DE_PRENSA_DE_LA_QUINIELA_DE_FECHA_17_03_20.pdf',
//         },
//       ],
//       imagenes: [],
//       preguntasFrecuentes: [],
//       paginasLibres: [],
//     },
//     elige8: { gameid: 'ELG8', relsorteoid_asociado: '1094513015', activo: '1' },
//     escrutinioElige8: [
//       {
//         tipo: '8 Acertados 8 ',
//         categoria: 1,
//         premio: '812,22',
//         ganadores: '36',
//       },
//     ],
//   },
//   {
//     fecha_sorteo: '2020-06-13 00:00:00',
//     dia_semana: 's\u00e1bado',
//     id_sorteo: '1094106014',
//     game_id: 'LAQU',
//     anyo: '2020',
//     numero: 14,
//     premio_bote: '1000000',
//     cdc: '10941',
//     apuestas: '3243053',
//     recaudacion: '243228975',
//     combinacion: '1 - X - 1 - 2 - 2 - 2 - 1 - X - 2 - 2 - X - 1 - 2 - X - 11',
//     premios: '133775936',
//     fondo_bote: '14634799',
//     escrutinio: [
//       { tipo: 'Pleno al 15 ', categoria: 1, premio: '0', ganadores: '0' },
//       {
//         tipo: '1\u00aa (14 Aciertos) ',
//         categoria: 2,
//         premio: '389166,36',
//         ganadores: '1',
//       },
//       {
//         tipo: '2\u00aa (13 Aciertos) ',
//         categoria: 3,
//         premio: '7296,87',
//         ganadores: '25',
//       },
//       {
//         tipo: '3\u00aa (12 Aciertos) ',
//         categoria: 4,
//         premio: '549,46',
//         ganadores: '332',
//       },
//       {
//         tipo: '4\u00aa (11 Aciertos) ',
//         categoria: 5,
//         premio: '70,54',
//         ganadores: '2586',
//       },
//       {
//         tipo: '5\u00aa (10 Aciertos) ',
//         categoria: 6,
//         premio: '14,68',
//         ganadores: '14916',
//       },
//     ],
//     partidos: [
//       {
//         posicion: 1,
//         idLocal: 564,
//         local: 'Granada',
//         idVisitante: 5,
//         visitante: 'Getafe',
//         signo: '1 ',
//         marcador: '2 - 1',
//         fecha: '12-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-12 19:30:00',
//       },
//       {
//         posicion: 2,
//         idLocal: 19,
//         local: 'Valencia',
//         idVisitante: 6,
//         visitante: 'Levante',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '12-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-12 22:00:00',
//       },
//       {
//         posicion: 3,
//         idLocal: 9,
//         local: 'Espanyol',
//         idVisitante: 374,
//         visitante: 'Alav\u00e9s',
//         signo: '1 ',
//         marcador: '2 - 0',
//         fecha: '13-06-2020',
//         hora: '14:00',
//         fecha_completa: '2020-06-13 14:00:00',
//       },
//       {
//         posicion: 4,
//         idLocal: 111,
//         local: 'Celta',
//         idVisitante: 20,
//         visitante: 'Villarreal',
//         signo: '2 ',
//         marcador: '0 - 1',
//         fecha: '13-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-13 17:00:00',
//       },
//       {
//         posicion: 5,
//         idLocal: 1151,
//         local: 'Legan\u00e9s',
//         idVisitante: 15,
//         visitante: 'Valladolid',
//         signo: '2 ',
//         marcador: '1 - 2',
//         fecha: '13-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-13 19:30:00',
//       },
//       {
//         posicion: 6,
//         idLocal: 10,
//         local: 'Mallorca',
//         idVisitante: 4,
//         visitante: 'Barcelona',
//         signo: '2 ',
//         marcador: '0 - 4',
//         fecha: '13-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-13 22:00:00',
//       },
//       {
//         posicion: 7,
//         idLocal: 12,
//         local: 'Real Madrid',
//         idVisitante: 124,
//         visitante: 'Eibar',
//         signo: '1 ',
//         marcador: '3 - 1',
//         fecha: '14-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-14 19:30:00',
//       },
//       {
//         posicion: 8,
//         idLocal: 125,
//         local: 'Real Sociedad',
//         idVisitante: 2,
//         visitante: 'Osasuna',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '14-06-2020',
//         hora: '22:00',
//         fecha_completa: '2020-06-14 22:00:00',
//       },
//       {
//         posicion: 9,
//         idLocal: 113,
//         local: 'M\u00e1laga',
//         idVisitante: 200,
//         visitante: 'Huesca',
//         signo: '2 ',
//         marcador: '1 - 3',
//         fecha: '12-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-12 19:30:00',
//       },
//       {
//         posicion: 10,
//         idLocal: 16,
//         local: 'Zaragoza',
//         idVisitante: 604,
//         visitante: 'Alcorc\u00f3n',
//         signo: '2 ',
//         marcador: '1 - 3',
//         fecha: '13-06-2020',
//         hora: '21:30',
//         fecha_completa: '2020-06-13 21:30:00',
//       },
//       {
//         posicion: 11,
//         idLocal: 7,
//         local: 'Deportivo',
//         idVisitante: 107,
//         visitante: 'Sporting',
//         signo: 'X ',
//         marcador: '0 - 0',
//         fecha: '14-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-14 17:00:00',
//       },
//       {
//         posicion: 12,
//         idLocal: 965,
//         local: 'Mirand\u00e9s',
//         idVisitante: 120,
//         visitante: 'Numancia',
//         signo: '1 ',
//         marcador: '2 - 1',
//         fecha: '14-06-2020',
//         hora: '17:00',
//         fecha_completa: '2020-06-14 17:00:00',
//       },
//       {
//         posicion: 13,
//         idLocal: 105,
//         local: 'Albacete',
//         idVisitante: 18,
//         visitante: 'Almer\u00eda',
//         signo: '2 ',
//         marcador: '0 - 1',
//         fecha: '14-06-2020',
//         hora: '19:30',
//         fecha_completa: '2020-06-14 19:30:00',
//       },
//       {
//         posicion: 14,
//         idLocal: 110,
//         local: 'C\u00e1diz',
//         idVisitante: 156,
//         visitante: 'Rayo Vallecano',
//         signo: 'X ',
//         marcador: '1 - 1',
//         fecha: '14-06-2020',
//         hora: '21:30',
//         fecha_completa: '2020-06-14 21:30:00',
//       },
//       {
//         posicion: 15,
//         idLocal: 1,
//         local: 'Athletic Club',
//         idVisitante: 3,
//         visitante: 'At. Madrid',
//         signo: '1-1',
//         marcador: '1 - 1',
//         fecha: '14-06-2020',
//         hora: '14:00',
//         fecha_completa: '2020-06-14 14:00:00',
//       },
//     ],
//     temporada: '2019-2020',
//     jornada: '42',
//     contenidosRelacionados: {
//       noticias: [
//         {
//           tituloRelacion: 'Bote Automatico',
//           tituloContenido: 'La Quiniela: bote de 1.000.000\u20ac',
//           urlContenido:
//             '/la-quiniela/botes/la-quiniela-bote-de-1-000-000euro-13-de-junio-de-2020',
//         },
//         {
//           tituloRelacion: 'Escrutinio Automatico',
//           tituloContenido:
//             'La Quiniela: premios y ganadores del 13 de junio de 2020',
//           urlContenido:
//             '/la-quiniela/escrutinios/la-quiniela-premios-y-ganadores-del-13-de-junio-de-2020',
//         },
//         {
//           tituloRelacion: 'Resultado Automatico',
//           tituloContenido: 'La Quiniela: resultados del 13 de junio de 2020',
//           urlContenido:
//             '/la-quiniela/resultados/la-quiniela-resultados-del-13-de-junio-de-2020',
//         },
//       ],
//       enlaces: [],
//       puntosDeVenta: [],
//       documentos: [
//         {
//           tituloRelacion: null,
//           tituloContenido:
//             'Nota de prensa de la jornada del 13/06/2020 La Quiniela',
//           urlContenido:
//             '/f/loterias/documentos/Quiniela/Notas de prensa/NOTA_DE_PRENSA_DE_LA_QUINIELA_DE_FECHA_13_06_20.pdf',
//         },
//       ],
//       imagenes: [],
//       preguntasFrecuentes: [],
//       paginasLibres: [],
//     },
//     elige8: { gameid: 'ELG8', relsorteoid_asociado: '1094113014', activo: '1' },
//     escrutinioElige8: [
//       {
//         tipo: '8 Acertados 8 ',
//         categoria: 1,
//         premio: '1548,22',
//         ganadores: '20',
//       },
//     ],
//   },
// ];
